meta_title: "Dreamstones"
meta_description: "Dreamstones is a leading design and build company for international clients looking to build or renovate overseas."
meta_image: "logo-light.png" # Une image dans votre dossier app/assets/images/
